package integration_test

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/chinmay/goslop/tests/integration"
)

// TestGenerateFixtureQuarantine writes tests/integration/fixture_quarantine.txt.
// Run: GOSLOP_GEN_QUARANTINE=1 go test ./tests/integration/ -run TestGenerateFixtureQuarantine -count=1
func TestGenerateFixtureQuarantine(t *testing.T) {
	if os.Getenv("GOSLOP_GEN_QUARANTINE") == "" {
		t.Skip("set GOSLOP_GEN_QUARANTINE=1 to regenerate fixture_quarantine.txt")
	}
	var keys []string

	// BP
	cases, err := integration.DiscoverBPCases()
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range cases {
		rule := integration.BPRuleID(c)
		opts := integration.DefaultMatrixOptions()
		opts.Only = []string{rule}
		for _, vuln := range []bool{true, false} {
			rel := integration.BPFixtureRel(c, vuln)
			res, scanErr := integration.MaterializeAndScanOpts(rel, opts)
			if scanErr != nil || (vuln && !integration.HasRule(res.Findings, rule)) || (!vuln && integration.HasRule(res.Findings, rule)) {
				keys = append(keys, rel)
			}
		}
	}
	// PERF
	pcases, err := integration.DiscoverPERFCases()
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range pcases {
		rule := integration.PERFRuleID(c)
		opts := integration.DefaultMatrixOptions()
		opts.Only = []string{rule}
		for _, vuln := range []bool{true, false} {
			rel := integration.PERFFixtureRel(c, vuln)
			res, scanErr := integration.MaterializeAndScanOpts(rel, opts)
			if scanErr != nil || (vuln && !integration.HasRule(res.Findings, rule)) || (!vuln && integration.HasRule(res.Findings, rule)) {
				keys = append(keys, rel)
			}
		}
	}
	// CWE
	ccases, err := integration.DiscoverCWECases()
	if err != nil {
		t.Fatal(err)
	}
	for _, cwe := range ccases {
		opts := integration.DefaultMatrixOptions()
		opts.TaintEnabled = true
		opts.Only = []string{cwe}
		for _, suite := range []string{"frameworks", "stdlib"} {
			for _, vuln := range []bool{true, false} {
				rel := integration.CWEFixtureRel(suite, cwe, vuln)
				res, scanErr := integration.MaterializeAndScanOpts(rel, opts)
				if scanErr != nil || (vuln && !integration.HasRule(res.Findings, cwe)) || (!vuln && integration.HasRule(res.Findings, cwe)) {
					keys = append(keys, rel)
				}
			}
		}
	}

	sort.Strings(keys)
	uniq := make([]string, 0, len(keys))
	prev := ""
	for _, k := range keys {
		k = filepath.ToSlash(k)
		if k == prev {
			continue
		}
		prev = k
		uniq = append(uniq, k)
	}

	root, err := integration.RepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	outPath := filepath.Join(root, "tests", "integration", integration.QuarantineFileName)
	var b strings.Builder
	b.WriteString("# Known fixture matrix gaps vs Rust heuristic oracles.\n")
	b.WriteString("# Generated by: GOSLOP_GEN_QUARANTINE=1 go test ./tests/integration/ -run TestGenerateFixtureQuarantine\n")
	b.WriteString("# Paths are relative to tests/fixtures/. Remove entries as detectors improve.\n")
	b.WriteString(fmt.Sprintf("# count=%d\n", len(uniq)))
	for _, k := range uniq {
		b.WriteString(k)
		b.WriteByte('\n')
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %d quarantine entries to %s", len(uniq), outPath)
}
